### ISSUE TITLE
ERROR: OpenCL driver API error (code: -1, file:/home/vsts/work/1/s/LinuxCompile/                                                           LuxCore/src/luxrays/devices/ocldevice.cpp, line: 89): CL_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by emily9the9strange** [LuxCoreRender/BlendLuxCore#664]
I am using luxcore v2.5 on Blender 9.92 
The installation and enabeling of the addon worked fine via terminal on ArchLinux.
Starting a rendering via Terminal it says it finds two openCL Platforms. Two seconds later it says it cannot find anything (the CL_DEVICE is not found)
On the one hand I do only want to render with CPU and would not need any CL devices. Yet I cannot suppress the CL Device Compiling. On the other hand I have read online that this problem was solved for v2.5 but I still got this error Message.

**Comment by Dade916** [comment]
You may have read about a different error (i.e. -1001 => CL_PLATFORM_NOT_FOUND_KHR). Your error is different and it looks like you have valid OpenCL platform available but it returns an error when I ask for the list of devices available.
It sounds like a broken Platform installation. Do you have PoCL or something like that ? Can you post here the log output with the list of platforms available.

I would simple remove the broken platform to solve your problem (check your '/etc/OpenCL' directory and installed packages).

**Comment by mroy-mmc** [comment]
I'm not entirely sure about ArchLinux but In generic Linux then there is always a dummy OpenCL device from Mesa and you need to disable it. That is easy enough to do.

ls /etc/OpenCL/vendors/

If you see a file called mesa.icd

then rename it to something like 
mesa.icd.old

(you need root privs) and then you should retry Luxcore. That's what I had to do to get Luxcore setting my nvidia device as an OpenCL device for testing.

**Comment by ebutts531** [comment]
For me, this was an issue when running Blender from a flatpak installation. Running blender from an extracted instance in its own folder seems to fix this issue.

**Comment by aimorris** [comment]
> I'm not entirely sure about ArchLinux but In generic Linux there is always a dummy OpenCL device from Mesa and you need to disable it. That is easy enough to do.
> 
> ls /etc/OpenCL/vendors/
> 
> If you see a file called mesa.icd
> 
> then rename it to something like
> mesa.icd.old
> 
> (you need root privs) and then you should retry Luxcore. That's what I had to do to get Luxcore setting my nvidia device as an OpenCL device for testing.
> 
> BTW are you using an NVidia or AMD GPU?

This worked for me.

**Comment by CodeFHD** [comment]
Closing this issue after a review with the following reasons/conclusions:
- Issue affected old Blender + LuxCore versions that are no longer supported
- At the time, issue was rated likely due to OpenCL installation (common issue; can't be fixed in BlendLuxCore) 
- An additional linux-specific solution was suggested by users, no follow-up from original author

If you feel this issue is still relevant in 2025, please re-test it with a recent Blender + LuxCore version, then ask to reopen and provide the following information:
- Operating System
- CPU + GPU model
- Blender and LuxCoreRender version used for re-test
- Detailed steps how to reproduce the bug from an empty scene,
- provide a specific .blend-file

**Comment by Orum** [comment]
This is still an issue with:

- Blender 4.2.8 LTS
- BlendLuxCore 2.9.4
- CPU: 7950X3D
- GPUs: Integrated (Raphael) + Nvidia GeForce RTX 4080 Super
- OS: Linux 6.12.19-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu, 13 Mar 2025 14:07:27 +0000 x86_64 GNU/Linux

Steps to reproduce:
1. Install Blender 4.2.8 and ensure default settings (I believe "File -> Defaults -> Load Factory Settings" followed by restarting Blender will do this).  Keep the default scene and don't change it.
2. Install BlendLuxCore 2.9.4 addon.
3. Change the Render Engine to "LuxCoreRender" from the "EEVEE" default.
4. Change the viewport render method to "Viewport Shading", and the error should appear.

I've also attached my clinfo output should it help.

[clinfo.txt](https://github.com/user-attachments/files/19348737/clinfo.txt)

**Comment by CodeFHD** [comment]
I have replicated the issue with a very similar setup:
- Blender 4.3.2
- BlendLuxCore Latest
- CPU: 8845HS
- GPUs: Integrated + RTX 4060M
- OS: Archlinux

My personal steps to reproduce:
- Originally, I had no OpenCL driver for AMD installed, only Nvidia was found, I had no issue
- Installed `opencl-rusticl-mesa` package --> The issue appeared
- Uninstalled the package --> The issue was gone
- Installed `rocm-opencl-runtime` --> No issue

A more interesting info came from `clinfo --list`
With the rocm-driver, I get two platforms (AMD + NVIDIA), and for each of them there is also a device listes
With rusticl, on the other hand, I also get two platforms, but the AMD platform shows no device.

After further reading about rusticl, I found the solution here:
https://docs.mesa3d.org/rusticl.html

After setting the environment variable
> $export RUSTICL_ENABLE=radeonsi
the device is detected and Blender starts.

Unfortunately, now comes the double-back, which is this already open issue: https://github.com/LuxCoreRender/LuxCore/issues/645,
which is that rendering with rusticl doesn't appear to work at the moment, so the use of rocm drivers would be needed.

I will keep this issue open for better visibility of known issues.

**Comment by Orum** [comment]
So, if my understanding is correct, the issue here is that the rusticl platform appears when enumerating all the OpenCL platforms, but has no devices listed in it?  That seems like it should be simple enough to fix, as we can just ignore all platforms with 0 devices.

I will dig into the code and hopefully be able to submit a PR for this.

**Comment by CodeFHD** [comment]
As I said, the environment variable `RUSTICL_ENABLE` already fixes this. And this variable is specified in the mesa docs.

Because of the other issue I linked, which I could now reproduce after these tests, I already opened an issue in the mesa issue tracker:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/12846

**Comment by Orum** [comment]
While I agree that this ultimately needs to be fixed upstream (as who wouldn't want rusticl to work), I also think that this should be patched within BlendLuxCore.  Otherwise, if this odd situation of 0 devices in a platform occurs again in the future, it'll just cause more problems.

**Comment by CodeFHD** [comment]
Ok, I think I had just misunderstood your last comment.

Filtering platforms with 0 devices sounds like a good idea, if it can be done.
Any help will be appreciated!

P.S.: This is the kind of case where I would like to have a warning not just somewhere in the console log, but with a popup window and a "Don't show this warning in the future option", so that it doesn't go by unnoticed when a GPU isn't available.
Now that we are using the extensions platform with custom python dependencies anyways, I wonder if we can make use of pyside6 or something similar. There is also some remnant of isntalling pyside2 in the code, but I don't see it used anywhere...

**Comment by Divinux** [comment]
Hi, just to add to this,
Blender 4.4.3
BlendLuxCore version: 2.10.0
Arch Linux-6.14.10-arch1
AMD Ryzen 7 5800X3D
Amd Radeon Vega 56


Had the same error (While the same same versions work on my Windows 10 install on the same machine flawlessly), installing and uninstalling the packages `opencl-rusticl-mesa` or `rocm-opencl-runtime` made no difference on their own, `clinfo --list` was a good hint from CodeFHD, I had the same result with rusticl appearing with no devices as such:

```
Platform #0: AMD Accelerated Parallel Processing
 `-- Device #0: gfx900:xnack-
Platform #1: rusticl
```
Doing `export OCL_ICD_VENDORS=/etc/OpenCL/vendors/amdocl64.icd` did remove the rusticl from the clinfo output, but made no difference either. Checking the vendors showed both amdocl64.icd and rusticl.icd:

```
$ ls /etc/OpenCL/vendors/
amdocl64.icd  rusticl.icd
```
Finally removing rusticl.icd by doing `sudo mv /etc/OpenCL/vendors/rusticl.icd /etc/OpenCL/vendors/rusticl.icd.disable` made LuxCore function properly.

**Comment by CodeFHD** [comment]
For the sake of updating open issues, the following ToDo-items still apply to this issue:

- [ ] Add a additional check in the respective BlendLuxCore Code (if possible) that filters OpenCL platform that do not contain any devices
- [ ] If such platforms are found, print a warning to the console to support future debugging
